@startuml sequence-resetpassword
actor 重置密码的人
重置密码的人 --> user_confirm: 发出改密码请求
user_confirm --> send_email: 如果没发过验证码，发
user_confirm --> post: 如果发过验证码，调用post
post --> 重置密码的人: 询问再发一个新的验证码还是进入填写验证码界面
重置密码的人 --> send_email: 选择再发一个新的
' TODO 再发一个新的到了send_email了还得回到user_confirm再到user_reset
重置密码的人 --> user_reset: 选择进入填写验证码界面
user_confirm --> user_reset: 让用户输验证码
user_reset --> user_changepass: 成功的话就改密码
user_changepass --> redirect: 回到登陆界面
@enduml