@startuml
actor 用户
用户 -> main: 输入参数生成题目
main -> generate
generate -> randint
generate -> set_lchild
generate ->set_rchild
generate -> deduplicate
deduplicate -> format_expression
format_expression -> deduplicate
deduplicate -> generate
generate -> to_string
generate -> calculator
calculator -> solve
solve -> calculator
calculator -> generate
generate -> round_up
generate -> changepowop
generate -> main
main -> answer
@enduml