# Generated by Django 2.2.7 on 2019-12-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
                ('answer_float', models.CharField(max_length=128)),
                ('answer_Fraction', models.CharField(max_length=128)),
                ('question_if_pow', models.BooleanField()),
                ('question_if_negative', models.BooleanField()),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
